### ISSUE TITLE
Guidance for materials

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PSPowerHour/PSPowerHour#3]
Need to establish a process for both accepting materials sourced here, and/or links to external sources (e.g. someone might have their own github repo of materials for a demo).

Might be worth aligning with agenda data in some way

**Comment by wsmelton** [comment]
Well you could do this with some GitHub magic but not sure you want to get that deep....using nested repositories. If their demo was in a dedicated repository you can simply nest that into this repository.

Another option would be you create a folder for each power hour, by date or whatever, and then the PR the presenter does simply creates their named folder and add the content. You can then have them link that PR to the issue of their presentation (e.g. add "fixes <their issue number>"), that way the issue is closed out and mapped to their specific content.

Would you use the Wiki for the agenda itself? Keeps everything in one place (e.g. this repository). Shoot you could utilize the projects and all the PRs for a given session becomes a release 😁 then folks can pull down all the material for that session by simply pulling the zip down of the "release".

Just spit balling here...

**Comment by glennsarti** [comment]
personally, (and quite an opinion here) use GithubPages :-) No Wiki

Just use PRs for adding agendas and a folder for each powerhour session

**Comment by RamblingCookieMonster** [comment]
Might move to GitHub pages down the line, but have some tooling to essentially generate the agenda, folder layout, and initial individual demo readmes for all this stuff.  Feel free to open a new issue if you have a specific idea!
